version: "3.8"

services:
  node:
    container_name: node
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
