version: "3.8"

services:
  node:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - mongo
    volumes:
      - ./:/reviews-api/server

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ReviewsApiPassword
    ports:
      - 3002:3002
    volumes:
      - ./:/reviews-api/db
